### ISSUE TITLE
q parameter in src/dockerfile

### ISSUE THREAD

**Issue by RyanWalker277** [Samagra-Development/PDF-Package#107]
**Describe the bug**
The `-q` parametere in `src/dockerfile` is not necessary. Sometimes the codebase setup takes a lot of times and sice the verbose output is silent , it seems as the installation is stuck.

**Comment by radhay-1199** [comment]
the time is long because we are installing a complete ubuntu image instead of some alpine version and `-q` was intentional to avoid redundant logs. we can add some kind of progress bar or loader to solve your stated issue, but it will be mostly user interaction improvement

**Comment by RyanWalker277** [comment]
Ya but I strongly believe we should add something there.Let it be a progress bar only. As a newbie it gets extremely confusing sometimes to figure out whether the installation is stuck or running. Will add this to the existing PR.
