### ISSUE TITLE
[C4GT]: UI to Manage and Use Google Docs for Creating Templates; Import Plugin

### ISSUE THREAD

**Issue by Shruti3004** [Samagra-Development/PDF-Package#120]
## Project Details
Most of the government workflows end up with a document that shows the key metrics that officers can take actions on. For example a school assessment report which can be printed and stuck to the notice board of school. A report card which can be verified digitally (like COWIN) with PDF as output is a good example for the same.

Doc generator is a plugin-based service that will help in generating reports, docs, pdfs, from various data sources and in any required format and layout. The Design Doc can be found [here](https://docs.google.com/document/d/1aX9OL_LKnkAojXyfvYLjSxXoUnhlYMjVkO9Obr0Fh0E/edit).

## Learning Path 

| Category | Rating |
| :-- | :-- |
| Complexity | Medium |
| Skills Required | Javascript, Typescript, React |
| Mentor | @Shruti3004  |
| Project size | 8 weeks |

**Comment by UdAyAn123** [comment]
I am experienced in developing Ui can you please add more details to the project

**Comment by VarunGitGood** [comment]
Hi @Shruti3004 so this is one of the projects under Doc Generator and i can submit a Proposal right?

**Comment by AnshulMalik** [comment]
We'll be tracking this issue in https://github.com/Samagra-Development/Doc-Generator/issues/123
