### ISSUE TITLE
Add pre-commit hook to run tests and format code

### ISSUE THREAD

**Issue by yuvrajsab** [Samagra-Development/PDF-Package#131]
We need to add a pre-commit hook to run the tests before anyone does `git commit` and if the tests pass then only it will create a commit otherwise it will throw an error. 

We recommend looking into this package [Husky](https://typicode.github.io/husky/) to achieve this. It will also be beneficial if we add a second hook to run `yarn format` to format our code for maintaining code consistency.

**Comment by VarunGitGood** [comment]
can i work on this?

**Comment by AnshulMalik** [comment]
Go ahead @varun7singh

**Comment by AnshulMalik** [comment]
This already has a PR @varun7singh

**Comment by VarunGitGood** [comment]
Sure
