### ISSUE TITLE
Fix AppController end-to-end testcase

### ISSUE THREAD

**Issue by yuvrajsab** [Samagra-Development/PDF-Package#132]
There is an e2e test case in this file `test/app.e2e-spec.ts` that simply hit the`/api` endpoint and tests if it prints `Doc Generator` or not. 
So currently this test case is failing because the required dependencies are not available to it for example Prisma service is not available to it, we can pass the instance but in this case, we don't want to pass the actual Prisma service instance rather we want to **mock** it because we don't want this test to be dependent on the database. 

See https://github.com/Samagra-Development/Doc-Generator/blob/Roadmap-2023/test/app.e2e-spec.ts#L10-L13 for reference.

**Comment by VarunGitGood** [comment]
Can i work on this?

**Comment by AnshulMalik** [comment]
Yes @varun7singh , assigning this to you.

**Comment by varun7singh** [comment]
@yuvrajsab 
this is what i get right now on running tests
![image](https://github.com/Samagra-Development/Doc-Generator/assets/73738410/9701a5ea-afc4-46f9-b1d6-5c8c75e52895)

**Comment by VarunGitGood** [comment]
Hii @yuvrajsab i did mock the PrismaService to resolve the dependecies issue just realized unable to find the "/api" endpoint in the controller

should i create one?

**Comment by VarunGitGood** [comment]
Okay so i changed the endpoint to "/" in the test as there was no endpoint present in the controller 
![image](https://github.com/Samagra-Development/Doc-Generator/assets/73738410/3db2a171-556c-43e2-97f5-36fde3654c70)


** Also i did change the file structure a little bit just for the PrismaService and Module i used the nest cli therefore all dependencies resolved by updating paths
