### ISSUE TITLE
Use strict typescript

### ISSUE THREAD

**Issue by yuvrajsab** [Samagra-Development/PDF-Package#133]
Change `tsconfig.json` to enable `strict` mode, `noImplicitAny`, `strictNullChecks`, `noFallthroughCasesInSwitch`, and `forceConsistentCasingInFileNames`? And add types wherever they are missing like in the controller, services, everywhere.

Reference: https://www.typescriptlang.org/tsconfig#Type_Checking_6248.

By using strict typescript it will help us write better and more robust code.

**Comment by l3hargav** [comment]
Hi, can i work on this?

**Comment by AnshulMalik** [comment]
@l3hargav Vaibhave already has a PR, that will most probably fix this. 

May be we can find another one for you.

**Comment by l3hargav** [comment]
@AnshulMalik Ah I see, that's fine i had only just started working on it. I feel that it'd be great to contribute to this project
