### ISSUE TITLE
update readme for local development

### ISSUE THREAD

**Issue by yuvrajsab** [Samagra-Development/PDF-Package#148]
Need to update the readme to add installation instructions for local development. 
The steps would be:

## Installation
Prerequisite
* node 16 and yarn 1
* docker
* docker-compose

Steps:
1. `cp .env.copy to .env`
2. `docker-compose -f docker-compose.local.yml up -d` - for running the services that our app needs.
3. `yarn install` - for installing app dependencies
4. `yarn start:dev` - start the server in watch mode

## Test
* `yarn test` for running unit tests
* `yarn test:e2e` for running end-to-end tests
* `yarn test:cov` for generating coverage reports for the tests

> Would also be good to delete `app` service from `docker-compose.local.yml` and replace env variables from `.env.copy` like RMQ_URL with `RMQ_URL=amqp://username:password@localhost:5672`, DATABASE_URL with `DATABASE_URL="postgresql://postgres:yoursupersecret@localhost:5432/db?schema=public"`

**Comment by FirePing32** [comment]
@yuvrajsab Should I add this ?

**Comment by FirePing32** [comment]
@yuvrajsab The app starts automatically after DB and broker is set up.

**Comment by yuvrajsab** [comment]
@FirePing32 We don't want to use docker for setting up the `app` service because it is making our local development process a little complex. what we want is to take out our `app` service from docker. So for that, you have to remove the `app` service block from docker-compose.local.yml and change the env variable in .env.copy with 
```
RMQ_URL=amqp://username:password@localhost:5672
DATABASE_URL="postgresql://postgres:yoursupersecret@localhost:5432/db?schema=public"
```

**Comment by FirePing32** [comment]
Ok @yuvrajsab. I will make a PR by EOD.

**Comment by Swatishree-Mahapatra** [comment]
Hello! I can work on updating the readme.md with the required steps to set-up locally. Can you assign me?

**Comment by AnshulMalik** [comment]
Hey @Swatishree-Mahapatra , this is done by @FirePing32 . We can have something else for you.
