### ISSUE TITLE
Automate Documentation Generation

### ISSUE THREAD

**Issue by NEGRAH-S** [Samagra-Development/PDF-Package#149]
Explore automated tools or frameworks that can generate documentation from source code or project annotations. This can help streamline the process and ensure that the documentation stays in sync with the codebase.

**Comment by VaibhaveS** [comment]
do you have any tools in mind?

**Comment by NEGRAH-S** [comment]
> do you have any tools in mind?

hello @VaibhaveS , I am working upon it . Will make  a PR soon on the same issue

**Comment by NEGRAH-S** [comment]
PR  #150   
has been made for the same .

**Comment by AnshulMalik** [comment]
@NEGRAH-S created a discussion for it, let's capture key points there.
https://github.com/Samagra-Development/Doc-Generator/discussions/155
